blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/dothq/browser/discussions/new?category_id=32000754
    about: Share your feature request with the community 
  - name: Ask questions, leave feedback and get support
    url: https://github.com/dothq/browser/discussions/new
    about: Create a thread in the Discussions tab